### Minimax Algorithm

In [8]:
import numpy as np

In [9]:
def CHK_Winner(M):
    x=0
    o=0
    # L TO R
    for i in range(3):
        cnt_x=0
        cnt_o=0
        for j in range(3):
            if M[i][j] == 1:
                cnt_x=cnt_x+1
                x=x+1
            if M[i][j] == -1:
                cnt_o=cnt_o+1
                o=o+1
            if(cnt_x==3):
                return 1
            if(cnt_o==3):
                return -1
    # T TO B
    for i in range(3):
        cnt_x=0
        cnt_o=0
        for j in range(3):
            if M[j][i] == 1:
                cnt_x=cnt_x+1
            if M[j][i] == -1:
                cnt_o=cnt_o+1
            if(cnt_x==3):
                return 1
            if(cnt_o==3):
                return -1
            
    # P DIAGONAL
    cnt_x=0
    cnt_o=0
    for i in range(3):
        
        if(M[i][i] == 1):
            cnt_x=cnt_x+1
        if M[i][i] == -1:
            cnt_o=cnt_o+1
    
    if(cnt_x==3):
        return 1
    if(cnt_o==3):
        return -1
    
    # S DIAGONAL
    cnt_x=0
    cnt_o=0
    for i in range(3):
        
        if(M[i][2-i] == 1):
            cnt_x=cnt_x+1
        if M[i][2-i] == -1:
            cnt_o=cnt_o+1       
    
    if(cnt_x==3):
        return 1
    if(cnt_o==3):
        return -1
    
    # Draw-check
    if(x+o == 9):
        return 0
    # Empty-check
    return 99
    
    

In [10]:
def Minimax(M,P):
    
    t = CHK_Winner(M)
    if(t==1 or t==-1 or t==0):
        return t,-1,-1
    
    gt = 0
    if(P==1):
        gt = -100
    else:
        gt = 100
    posX = -1
    posY = -1
    
    for i in range(3):
        for j in range(3):
            
            if(M[i][j]==0):
                
                TM = M.copy()
                TM[i][j]=P
                if(P==1):
                    t,x,y=Minimax(TM,-1)
                else:
                    t,x,y=Minimax(TM,1)
                    
                if(P==1):
                    if(gt<t):
                        gt = t
                        posX,posY = i,j
                else:
                    if(gt>t):
                        gt = t
                        posX,posY = i,j
                        
    return gt,posX,posY

In [11]:
def Play():
    M = np.zeros((3,3))
    cx,cy=(10,10)
    W=99
    while(W==99):
        
        hx = int(input('PX = '))
        hy = int(input('PY = '))
        M[hx][hy]=-1
        print("H Turn")
        
        W = CHK_Winner(M)
        print(M)
        if(W == -1):
            print('H Winner')
            break
        
        v,cx,cy = Minimax(M,1)
        if cx!=-1 and cy !=-1:
            M[cx][cy]=1
            print("C Turn")
            print(M)
            W = CHK_Winner(M)
            if(W == 1):
                print('C Winner')
                break
        
        W = CHK_Winner(M)
    
    if(W == 99):
        print('Match Draw!')
        

In [12]:
Play()

PX = 0
PY = 0
H Turn
[[-1.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
C Turn
[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]]
PX = 1
PY = 0
H Turn
[[-1.  0.  0.]
 [-1.  1.  0.]
 [ 0.  0.  0.]]
C Turn
[[-1.  0.  0.]
 [-1.  1.  0.]
 [ 1.  0.  0.]]
PX = 0
PY = 2
H Turn
[[-1.  0. -1.]
 [-1.  1.  0.]
 [ 1.  0.  0.]]
C Turn
[[-1.  1. -1.]
 [-1.  1.  0.]
 [ 1.  0.  0.]]
PX = 1
PY = 2
H Turn
[[-1.  1. -1.]
 [-1.  1. -1.]
 [ 1.  0.  0.]]
C Turn
[[-1.  1. -1.]
 [-1.  1. -1.]
 [ 1.  1.  0.]]
C Winner
